import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/styles/normalize.scss';

const roboto = Roboto({
	weight: ['400', '500', '700'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'YouTube Music Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko' className={roboto.className}>
			<body>{children}</body>
		</html>
	);
}
