import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import ToggleMenuProvider from './_components/layout/ToggleMenuProvider';
import GuideWrapper from './_components/layout/GuideWrapper';
import NavBarWrapper from './_components/layout/NavBarWrapper';
import SetupWorker from './_components/common/SetupWorker';
import styles from './main.module.scss';
import '@/styles/global.scss';

const roboto = Roboto({
	weight: ['400', '500', '700'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'YouTube Music Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko' className={roboto.className}>
			<body>
				<SetupWorker />
				<ToggleMenuProvider>
					<NavBarWrapper />
					<GuideWrapper />
					<main className={styles.mainContent}>{children}</main>
				</ToggleMenuProvider>
			</body>
		</html>
	);
}
